allowBuilds:
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  '@parcel/watcher': true
  electron-winstaller: true
  esbuild: true
  tldjs: true
  vue-demi: true

managePackageManagerVersions: true

minimumReleaseAge: 10080

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'
  - esbuild
  - vue-demi
